<?php

/**
 * @file
 * Main module file for kdog module.
 */

/**
 * watchdog() replacement which behaves more like dpm().
 *
 * @param mixed $input Any input you would usually pass as the first parameter
 *  to dpm().
 * @param string $name The very first portion of the logged message.
 * @param constant $severity One of the WATCHDOG_* severity levels.
 */
function kdog($input, $name = 'kdog debug output', $severity = WATCHDOG_DEBUG) {
  $message = "<span>$name => </span>" . kdog_css() . kprint_r($input, TRUE);
  watchdog('kdog', '!message', array('!message' => $message), $severity);
}

/**
 * Hacked mess of krumo::_css() which returns the css and js for krumo to work.
 */
function kdog_css() {
  $output = '';
  $css = '';
  // DEVEL: changed for Drupal variables system
  $skin = variable_get('devel_krumo_skin', 'orange');

  // custom selected skin?
  $_ = KRUMO_DIR . "skins/{$skin}/skin.css";
  if ($fp = @fopen($_, 'r', 1)) {
    $css = fread($fp, filesize($_));
    fclose($fp);
  }

  // default skin?
  if (!$css && ($skin != 'default')) {
    $skin = 'default';
    $_ = KRUMO_DIR . "skins/default/skin.css";
    $css = join('', @file($_));
  }

  // print?
  if ($css != '') {

    // DEVEL: changed for Drupal path system.
    $css_path = drupal_get_path('module', 'devel') . "/krumo/skins/{$skin}/";
    $css_url = file_create_url($css_path);

    $css = preg_replace('~%url%~Uis', $css_url, $css);
    $js = join(file(KRUMO_DIR . "krumo.js"));

    $output = <<<EOF
    <style type="text/css">
      <!--/**/
        $css

      /**/-->
    </style>
    <script type="text/javascript">
      <!--//
        $js

      //-->
    </script>
EOF;
  }

  return $output;
}
